apiVersion: v2
name: borg-server
description: |
  The borg-server helm chart provides a minimally scalable setup by providing a pod with
    * SSSD for user discovery and auth (including providing SSH public keys)
    * SSHD + borg utilizing the SSSD via a common unix socket

  Note that currently the containers must be run as root since a rootless version: 0.1.0
  including improper privilege separation.
maintainers:
  - name: phihos
    email: philipp.hossner@posteo.de
    url: https://github.com/phihos
type: application
version: 0.1.16
# renovate: image=ghcr.io/borg-fleet/borg
appVersion: "2024-05-12"
