apiVersion: v2
name: borg-server
description: |
  The borg-server helm chart provides a minimally scalable setup by providing a pod with
    * SSSD for user discovery and auth (including providing SSH public keys)
    * SSHD + borg utilizing the SSSD via a common unix socket
  
  Note that currently the containers must be run as root since a rootless version comes with significant drawbacks
  including improper privilege separation.

maintainers:
  - name: phihos
    email: philipp.hossner@posteo.de
    url: https://github.com/phihos

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2023-01-29"
