apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-sssd
  namespace: default
data:
  SSSD_CONFIG: |+
    {{- range $section, $sectionContent := .Values.config.sssd }}
    [{{ $section }}]
    {{- range $key, $value := $sectionContent }}
    {{ $key }} = {{ $value }}
    {{- end }}
    {- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-ssh
  namespace: default
data:
  SSHD_CONFIG: |+
    {{- range $key, $value := .Values.config.sshd }}
    {{ $key }} {{ $value }}
    {{- end }}
