apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-sssd
data:
  SSSD_CONF: |
    {{- range $section, $sectionContent := .Values.config.sssd }}
    [{{ $section }}]
    {{- range $key, $value := $sectionContent }}
    {{ $key }} = {{ $value }}
    {{- end }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-sshd
data:
  SSHD_CONF: |
    {{- range $key, $value := .Values.config.sshd }}
    {{ $key }} {{ $value }}
    {{- end }}
