apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-sssd
  labels:
    {{- include "borg-server.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  SSSD_CONF: |
    {{- range $section, $sectionContent := .Values.config.sssd }}
    [{{ $section }}]
    {{- range $key, $value := $sectionContent }}
    {{ $key }} = {{ $value }}
    {{- end }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-sshd
  labels:
    {{- include "borg-server.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  SSHD_CONF: |
    {{- range $key, $value := .Values.config.sshd }}
    {{ $key }} {{ $value }}
    {{- end }}
{{- range $suffix, $configData := .Values.config.additionalConfigMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-{{ $suffix }}
  labels:
    {{- include "borg-server.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with $configData }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
