apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "borg-server.fullname" . }}
  labels:
    {{- include "borg-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "borg-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "borg-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "borg-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext.borg | nindent 12 }}
          image: "{{ .Values.image.borg.repository }}:{{ .Values.image.borg.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.borg.pullPolicy }}
          ports:
            - name: ssh
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources.borg | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config-sshd
          volumeMounts:
            - mountPath: /var/lib/sss/pipes
              name: sssd-pipes
            {{- if .Values.additionalVolumeMounts.borg }}
            {{ toYaml .Values.additionalVolumeMounts.borg | indent 12}}
            {{- end }}
        - name: {{ .Chart.Name }}-sssd
          securityContext:
            {{- toYaml .Values.securityContext.sssd | nindent 12 }}
          image: "{{ .Values.image.sssd.repository }}:{{ .Values.image.sssd.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.sssd.pullPolicy }}
          resources:
            {{- toYaml .Values.resources.sssd | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config-sssd
          volumeMounts:
            - mountPath: /var/lib/sss/pipes
              name: sssd-pipes
            {{- if .Values.additionalVolumeMounts.sssd }}
            {{ toYaml .Values.additionalVolumeMounts.sssd | nindent 12}}
            {{- end }}
      volumes:
        - name: sssd-pipes
          emptyDir: {}
        {{- if .Values.additionalVolumes }}
        {{ toYaml .Values.additionalVolumes | nindent 8}}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
