{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "borg-server.fullname" . }}
  labels: {{- include "borg-server.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}