{{- $labels := include "borg-server.labels" . -}}
{{- $annotations := .Values.config.annotations -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sshd-config-mounts
  labels:
    {{- $labels | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  {{- range $key, $value := .Values.config.sshd_config_mounts }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
