apiVersion: v1
kind: Service
metadata:
  name: {{ include "borg-server.fullname" . }}
  labels:
    {{- include "borg-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "borg-server.selectorLabels" . | nindent 4 }}
