apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: default
data:
  sssd.conf: |+
    {{- range $section, $sectionContent := .Values.config }}
    [{{ $section }}]
    {{- range $key, $value := $sectionContent }}
    {{ $key }} = {{ $value }}
    {{- end }}
    {- end }}
